service: serverless-inventory
provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
          Resource: "*"
functions:
  createItem:
    handler: handler.create_item
    events:
      - http:
          path: /items
          method: post
          cors: true
  getItem:
    handler: handler.get_item
    events:
      - http:
          path: /items/{id}
          method: get
          cors: true
resources:
  Resources:
    InventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InventoryTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DashboardBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: inventory-dashboard-395413310751>
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: inventory-dashboard-395413310751>
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: "arn:aws:s3:::inventory-dashboard-395413310751/*"